# Generated by Django 4.2.30 on 2026-09-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_telefono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
