# Generated by Django 4.2.30 on 2026-09-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id_comp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, db_column='dirección', max_length=200)),
                ('telefono', models.CharField(blank=True, db_column='teléfono', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Compañías',
                'db_table': 'compania',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_i', models.CharField(blank=True, max_length=80)),
                ('unidad_m', models.CharField(blank=True, max_length=20)),
                ('costo_uni', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mant', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_in', models.DateField(auto_now_add=True)),
                ('fecha_ter', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=30)),
                ('costo_t', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('respon', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'mantencion',
            },
        ),
        migrations.CreateModel(
            name='TipoMantencion',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categ', models.CharField(blank=True, max_length=50)),
                ('perio', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de mantención',
                'verbose_name_plural': 'Tipos de mantención',
                'db_table': 'tipomantencion',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehi', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('tipo_v', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('anio', models.IntegerField(blank=True, db_column='año', null=True)),
                ('estado', models.CharField(default='operativo', max_length=30)),
                ('kilometraje', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_compania', models.ForeignKey(db_column='id_compania', on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='core.compania')),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('rol', models.CharField(max_length=50)),
                ('id_compania', models.ForeignKey(blank=True, db_column='id_compania', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.compania')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_noti', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_n', models.CharField(blank=True, max_length=50)),
                ('fecha_en', models.DateField(auto_now_add=True)),
                ('desti', models.CharField(blank=True, max_length=150)),
                ('id_mant', models.ForeignKey(db_column='id_mant', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.mantencion')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.AddField(
            model_name='mantencion',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.PROTECT, related_name='mantenciones', to='core.tipomantencion'),
        ),
        migrations.AddField(
            model_name='mantencion',
            name='id_vehi',
            field=models.ForeignKey(db_column='id_vehi', on_delete=django.db.models.deletion.CASCADE, related_name='mantenciones', to='core.vehiculo'),
        ),
        migrations.CreateModel(
            name='MantencionInsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('costo_aso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_insu', models.ForeignKey(db_column='id_insu', on_delete=django.db.models.deletion.PROTECT, related_name='mantenciones', to='core.insumo')),
                ('id_mant', models.ForeignKey(db_column='id_mant', on_delete=django.db.models.deletion.CASCADE, related_name='insumos_usados', to='core.mantencion')),
            ],
            options={
                'db_table': 'mantencion_insu',
                'unique_together': {('id_mant', 'id_insu')},
            },
        ),
        migrations.CreateModel(
            name='MantencionEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_tra', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('costo_aso', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('id_emp', models.ForeignKey(db_column='id_emp', on_delete=django.db.models.deletion.PROTECT, related_name='mantenciones', to='core.empleados')),
                ('id_mant', models.ForeignKey(db_column='id_mant', on_delete=django.db.models.deletion.CASCADE, related_name='empleados_asignados', to='core.mantencion')),
            ],
            options={
                'db_table': 'mantencion_emp',
                'unique_together': {('id_mant', 'id_emp')},
            },
        ),
    ]
