# Generated by Django 4.2.30 on 2026-09-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='proxima_mantencion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
