# Generated by Django 4.2.30 on 2026-09-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_notificacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mantencionemp',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mantencionemp',
            name='id_emp',
        ),
        migrations.RemoveField(
            model_name='mantencionemp',
            name='id_mant',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.DeleteModel(
            name='MantencionEmp',
        ),
    ]
